apiVersion: v1
kind: Service
metadata:
  name: healthcare-backend-service
  labels:
    app: healthcare-backend
spec:
  type: NodePort
  selector:
    app: healthcare-backend
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
    nodePort: 30080
