apiVersion: apps/v1
kind: Deployment
metadata:
  name: healthcare-frontend
  labels:
    app: healthcare-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: healthcare-frontend
  template:
    metadata:
      labels:
        app: healthcare-frontend
    spec:
      containers:
      - name: frontend
        image: healthcare-frontend:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
        env:
        - name: REACT_APP_BACKEND_URL
          value: "http://healthcare-backend-service:5000"

        # Startup Probe - allows slow-starting containers to initialize
        startupProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 10
          failureThreshold: 30
          successThreshold: 1
          timeoutSeconds: 5

        # Liveness Probe - checks if the application is alive
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 20
          failureThreshold: 3
          successThreshold: 1
          timeoutSeconds: 5

        # Readiness Probe - checks if the application is ready to serve traffic
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 15
          periodSeconds: 10
          failureThreshold: 3
          successThreshold: 1
          timeoutSeconds: 5

        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
