apiVersion: v1
kind: Service
metadata:
  name: healthcare-frontend-service
  labels:
    app: healthcare-frontend
spec:
  type: NodePort
  selector:
    app: healthcare-frontend
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
    nodePort: 30083
